In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import datetime

import random

In [4]:
df= pd.read_csv('Crash_Analysis_System_(CAS)_data.csv')

In [118]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'advisorySpeed', 'areaUnitID', 'bicycle',
       'bridge', 'bus', 'carStationWagon', 'cliffBank',
       'crashDirectionDescription', 'crashFinancialYear', 'crashLocation1',
       'crashLocation2', 'crashRoadSideRoad', 'crashSeverity',
       'crashSHDescription', 'crashYear', 'debris', 'directionRoleDescription',
       'ditch', 'fatalCount', 'fence', 'flatHill', 'guardRail', 'holiday',
       'houseOrBuilding', 'intersection', 'kerb', 'light', 'meshblockId',
       'minorInjuryCount', 'moped', 'motorcycle', 'NumberOfLanes',
       'objectThrownOrDropped', 'otherObject', 'otherVehicleType', 'overBank',
       'parkedVehicle', 'pedestrian', 'phoneBoxEtc', 'postOrPole', 'region',
       'roadCharacter', 'roadLane', 'roadSurface', 'roadworks', 'schoolBus',
       'seriousInjuryCount', 'slipOrFlood', 'speedLimit', 'strayAnimal',
       'streetLight', 'suv', 'taxi', 'temporarySpeedLimit', 'tlaId', 'tlaName',
       'trafficControl', 'trafficIsland', 'trafficSign', 'train', 'tree',
       'truck', 'unknownVehicleType', 'urban', 'vanOrUtility', 'vehicle',
       'waterRiver', 'weatherA', 'weatherB'],
      dtype='object')

In [20]:
df.dtypes

X                float64
Y                float64
OBJECTID           int64
advisorySpeed    float64
areaUnitID       float64
                  ...
vanOrUtility     float64
vehicle          float64
waterRiver       float64
weatherA          object
weatherB          object
Length: 72, dtype: object

In [18]:
dataReducida = df.loc[df["crashYear"]>2023, :]

In [24]:
num_cols = [c for c in dataReducida.columns if dataReducida[c].dtype in ['float64', 'int64']]

In [22]:
cat_cols = [c for c in dataReducida.columns if dataReducida[c].dtype == 'O']

In [82]:
cat_cols

['crashDirectionDescription',
 'crashFinancialYear',
 'crashLocation1',
 'crashLocation2',
 'crashSeverity',
 'crashSHDescription',
 'directionRoleDescription',
 'flatHill',
 'holiday',
 'light',
 'region',
 'roadCharacter',
 'roadLane',
 'roadSurface',
 'streetLight',
 'tlaName',
 'trafficControl',
 'urban',
 'weatherA',
 'weatherB']

In [ ]:
for cat_col in cat_cols_analisis:
    for num_col in num_cols_analisis:
        # Crear figura
        plt.figure(figsize=(8, 6))
        
        dataReducida.boxplot(column=num_col, by=cat_col, grid=True, patch_artist=True,
                    boxprops=dict(facecolor='lightblue', color='blue'),
                    whiskerprops=dict(color='blue'),
                    flierprops=dict(marker='o', color='red', markersize=5),
                    capprops=dict(color='blue'))

        # Personalizar gráfico
        plt.title(f"Boxplot: {num_col} vs {cat_col}")
        plt.suptitle('')  
        plt.xlabel(cat_col)
        plt.ylabel(num_col)
        plt.xticks(rotation=45)  
        plt.grid(True)

        plt.show()

In [36]:
num_cols_analisis =['X', 'Y', 'fatalCount', 'carStationWagon', 'motorcycle']

In [68]:
# Mostrar los valores únicos en la columna 'light'
valores_unicos_light = dataReducida['holiday'].unique()

print(valores_unicos_light)

[nan 'Christmas New Year' 'Easter' 'Queens Birthday' 'Labour Weekend']

In [84]:
cat_cols_analisis =['region', 'holiday', 'weatherA','urban', 'flatHill','roadCharacter']

In [86]:
frequencia = dataReducida.groupby(cat_cols_analisis, as_index=False).agg({
    'OBJECTID': 'count'
})

frequencia.columns = cat_cols_analisis + ["frecuencia"]

In [88]:
frequencia

,region,holiday,weatherA,urban,flatHill,roadCharacter,frecuencia
0,Auckland Region,Christmas New Year,Fine,Open,Flat,Bridge,2
1,Auckland Region,Christmas New Year,Fine,Open,Flat,Motorway ramp,2
2,Auckland Region,Christmas New Year,Fine,Open,Flat,Nil,12
3,Auckland Region,Christmas New Year,Fine,Open,Hill Road,Nil,2
4,Auckland Region,Christmas New Year,Fine,Urban,Flat,Nil,31
...,...,...,...,...,...,...,...
319,West Coast Region,Labour Weekend,Light rain,Open,Flat,Nil,1
320,West Coast Region,Queens Birthday,Fine,Open,Hill Road,Nil,1
321,West Coast Region,Queens Birthday,Fine,Urban,Flat,Nil,1
322,West Coast Region,Queens Birthday,Light rain,Open,Flat,Nil,1
323,West Coast Region,Queens Birthday,Light rain,Open,Hill Road,Nil,1

In [104]:
dataReducida.shape[0]

18622

In [103]:
transformacion = {}
columnas = []

for c in num_cols:
    transformacion[c] = [ 
        ('lower_bound', lambda x: x.quantile(0.25) - 1.5 * (x.quantile(0.75) - x.quantile(0.25))),
        ('upper_bound', lambda x: x.quantile(0.75) + 1.5 * (x.quantile(0.75) - x.quantile(0.25)))
    ]
    columnas.append(f"{c}_lower_bound")
    columnas.append(f"{c}_upper_bound")

df_resultados = dataReducida.groupby(cat_cols_analisis, as_index=False).agg(transformacion)

In [154]:
transformacion2 = {}
columnas2 = []

for c in num_cols_analisis:
    transformacion2[c] = [ 
        ('lower_bound', lambda x: x.quantile(0.25) - 1.5 * (x.quantile(0.75) - x.quantile(0.25))),
        ('upper_bound', lambda x: x.quantile(0.75) + 1.5 * (x.quantile(0.75) - x.quantile(0.25)))
    ]
    columnas2.append(f"{c}_lower_bound")
    columnas2.append(f"{c}_upper_bound")

df_resultados2 = dataReducida.groupby(cat_cols_analisis, as_index=False).agg(transformacion2)
df_resultados2.columns = cat_cols_analisis + columnas2

In [156]:
df_resultados2.columns

Index(['region', 'holiday', 'weatherA', 'urban', 'flatHill', 'roadCharacter',
       'X_lower_bound', 'X_upper_bound', 'Y_lower_bound', 'Y_upper_bound',
       'fatalCount_lower_bound', 'fatalCount_upper_bound',
       'carStationWagon_lower_bound', 'carStationWagon_upper_bound',
       'motorcycle_lower_bound', 'motorcycle_upper_bound'],
      dtype='object')

In [290]:
df_bound = dataReducida.merge(
    df_resultados2,
    on=cat_cols_analisis,
    how="inner"  
)

In [292]:
df_bound.loc[((df_bound["fatalCount"] < df_bound["fatalCount_upper_bound"]) & (df_bound["fatalCount"] > df_bound["fatalCount_lower_bound"])), :]

,X,Y,OBJECTID,advisorySpeed,areaUnitID,bicycle,bridge,bus,carStationWagon,cliffBank,...,X_lower_bound,X_upper_bound,Y_lower_bound,Y_upper_bound,fatalCount_lower_bound,fatalCount_upper_bound,carStationWagon_lower_bound,carStationWagon_upper_bound,motorcycle_lower_bound,motorcycle_upper_bound
21,1.678607e+06,6.113141e+06,744584,NaN,500402.0,0.0,0.0,0.0,0.0,0.0,...,1.667101e+06,1.694601e+06,5.957348e+06,6.174432e+06,-0.375,0.625,0.000,2.000,0.000,0.000
43,1.788521e+06,5.784775e+06,754249,NaN,531301.0,0.0,NaN,0.0,1.0,NaN,...,1.747252e+06,1.847796e+06,5.766353e+06,5.817953e+06,-0.750,1.250,-0.250,1.750,-0.750,1.250
55,1.737039e+06,5.932763e+06,757586,45.0,506653.0,0.0,0.0,0.0,0.0,0.0,...,1.722331e+06,1.741942e+06,5.908366e+06,6.005955e+06,-0.500,1.500,-0.500,1.500,-0.500,1.500
79,1.611675e+06,6.146484e+06,762046,NaN,500207.0,0.0,0.0,0.0,1.0,0.0,...,1.573432e+06,1.717315e+06,6.042070e+06,6.169727e+06,-0.375,0.625,-1.875,3.125,-0.375,0.625
122,1.851992e+06,5.904418e+06,789221,NaN,533603.0,0.0,NaN,0.0,0.0,NaN,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
143,1.881203e+06,5.782222e+06,797281,NaN,538811.0,0.0,0.0,0.0,1.0,1.0,...,1.825679e+06,1.963648e+06,5.768666e+06,5.844650e+06,-0.375,0.625,1.000,1.000,0.000,0.000
203,1.871365e+06,5.817104e+06,805781,NaN,536514.0,0.0,0.0,0.0,1.0,0.0,...,1.825679e+06,1.963648e+06,5.768666e+06,5.844650e+06,-0.375,0.625,1.000,1.000,0.000,0.000
227,1.879434e+06,5.815840e+06,808383,NaN,536641.0,0.0,0.0,0.0,1.0,1.0,...,1.825679e+06,1.963648e+06,5.768666e+06,5.844650e+06,-0.375,0.625,1.000,1.000,0.000,0.000
271,1.839597e+06,5.590430e+06,812501,NaN,558600.0,0.0,NaN,0.0,1.0,NaN,...,1.799657e+06,1.852910e+06,5.555381e+06,5.695578e+06,-1.000,3.000,1.000,1.000,0.000,0.000
283,1.812970e+06,5.660529e+06,813464,NaN,532601.0,0.0,0.0,0.0,1.0,1.0,...,1.799657e+06,1.852910e+06,5.555381e+06,5.695578e+06,-1.000,3.000,1.000,1.000,0.000,0.000
298,1.727234e+06,5.981558e+06,815279,NaN,506613.0,0.0,0.0,0.0,1.0,1.0,...,1.722331e+06,1.741942e+06,5.908366e+06,6.005955e+06,-0.500,1.500,-0.500,1.500,-0.500,1.500
313,1.831662e+06,5.810575e+06,830148,NaN,534604.0,0.0,NaN,0.0,0.0,NaN,...,1.747252e+06,1.847796e+06,5.766353e+06,5.817953e+06,-0.750,1.250,-0.250,1.750,-0.750,1.250
357,1.815336e+06,5.821510e+06,838269,NaN,527125.0,0.0,NaN,0.0,1.0,NaN,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
391,1.845448e+06,5.855959e+06,842298,NaN,534200.0,0.0,0.0,0.0,1.0,1.0,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
409,1.816811e+06,5.912947e+06,843411,NaN,533200.0,0.0,0.0,0.0,1.0,0.0,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
447,1.701331e+06,6.045280e+06,845402,NaN,501809.0,0.0,0.0,0.0,1.0,0.0,...,1.667101e+06,1.694601e+06,5.957348e+06,6.174432e+06,-0.375,0.625,0.000,2.000,0.000,0.000
451,1.824122e+06,5.898379e+06,845746,NaN,533603.0,0.0,NaN,0.0,1.0,NaN,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
468,1.877613e+06,5.821018e+06,847576,NaN,538102.0,0.0,NaN,0.0,1.0,NaN,...,1.806590e+06,2.000851e+06,5.767745e+06,5.859429e+06,-0.750,1.250,0.250,2.250,-0.750,1.250
521,1.974743e+06,5.783235e+06,853214,45.0,542800.0,0.0,NaN,0.0,1.0,NaN,...,1.806590e+06,2.000851e+06,5.767745e+06,5.859429e+06,-0.750,1.250,0.250,2.250,-0.750,1.250
529,1.789642e+06,5.814443e+06,854199,NaN,527913.0,0.0,NaN,0.0,2.0,NaN,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
663,1.793039e+06,5.724502e+06,862508,NaN,531800.0,0.0,0.0,0.0,1.0,1.0,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
677,1.812379e+06,5.841292e+06,862869,NaN,527111.0,0.0,0.0,0.0,0.0,0.0,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
712,1.781390e+06,5.786630e+06,863983,NaN,531301.0,0.0,0.0,0.0,1.0,1.0,...,1.747252e+06,1.847796e+06,5.766353e+06,5.817953e+06,-0.750,1.250,-0.250,1.750,-0.750,1.250
744,1.678583e+06,6.019177e+06,864736,NaN,504501.0,0.0,NaN,0.0,2.0,NaN,...,1.667101e+06,1.694601e+06,5.957348e+06,6.174432e+06,-0.375,0.625,0.000,2.000,0.000,0.000
755,1.686754e+06,6.094271e+06,864893,75.0,501633.0,0.0,0.0,0.0,2.0,0.0,...,1.573432e+06,1.717315e+06,6.042070e+06,6.169727e+06,-0.375,0.625,-1.875,3.125,-0.375,0.625
788,1.814743e+06,5.801802e+06,865518,NaN,527931.0,0.0,0.0,0.0,1.0,0.0,...,1.794765e+06,1.841736e+06,5.688539e+06,6.024283e+06,-1.500,2.500,1.000,1.000,0.000,0.000
805,1.632626e+06,6.113646e+06,865948,NaN,500202.0,0.0,0.0,0.0,0.0,0.0,...,1.573432e+06,1.717315e+06,6.042070e+06,6.169727e+06,-0.375,0.625,-1.875,3.125,-0.375,0.625
963,1.881262e+06,5.829077e+06,869413,NaN,536810.0,0.0,NaN,0.0,2.0,NaN,...,1.806590e+06,2.000851e+06,5.767745e+06,5.859429e+06,-0.750,1.250,0.250,2.250,-0.750,1.250

In [294]:
for num_col in num_cols_analisis:
    # Mostrar el número de filas antes del procesamiento
    print(f"Row: {df_bound.shape[0]} - {num_col}: processing...")
    
    # Guardar el número de filas antes de la limpieza
    rows_before = df_bound.shape[0]
    
    # Realizar la limpieza de los valores atípicos
    df_bound = df_bound.loc[
        (df_bound[num_col] >= df_bound[f"{num_col}_lower_bound"]) 
        &
        (df_bound[num_col] <= df_bound[f"{num_col}_upper_bound"]),
        :
    ]
    
    # Calcular la cantidad de valores eliminados
    rows_after = df_bound.shape[0]
    removed_rows = rows_before - rows_after
    
    # Imprimir cuántos valores atípicos fueron eliminados
    print(f"Se eliminaron {removed_rows} valores atípicos en la columna {num_col}.")
    print(f"Quedan {rows_after} registros en total.")

Row: 994 - X: processing...
Se eliminaron 50 valores atípicos en la columna X.
Quedan 944 registros en total.
Row: 944 - Y: processing...
Se eliminaron 36 valores atípicos en la columna Y.
Quedan 908 registros en total.
Row: 908 - fatalCount: processing...
Se eliminaron 7 valores atípicos en la columna fatalCount.
Quedan 901 registros en total.
Row: 901 - carStationWagon: processing...
Se eliminaron 37 valores atípicos en la columna carStationWagon.
Quedan 864 registros en total.
Row: 864 - motorcycle: processing...
Se eliminaron 28 valores atípicos en la columna motorcycle.
Quedan 836 registros en total.

In [170]:
dataReducida.shape[0]

18622

In [172]:
df_resultados2.shape[0]

324

In [236]:
df_clean = df_bound.loc[:,cat_cols_analisis +num_cols]

In [238]:
df_clean

,region,holiday,weatherA,urban,flatHill,roadCharacter,X,Y,OBJECTID,advisorySpeed,...,tlaId,trafficIsland,trafficSign,train,tree,truck,unknownVehicleType,vanOrUtility,vehicle,waterRiver
0,Auckland Region,Christmas New Year,Fine,Urban,Flat,Nil,1.759311e+06,5.909998e+06,716368,NaN,...,76.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,NaN
1,Waikato Region,Easter,Fine,Open,Flat,Nil,1.817852e+06,5.797014e+06,718777,NaN,...,17.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Auckland Region,Christmas New Year,Fine,Urban,Flat,Nil,1.752382e+06,5.916235e+06,722390,NaN,...,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Hawke's Bay Region,Christmas New Year,Fine,Open,Flat,Nil,1.932780e+06,5.605791e+06,725025,NaN,...,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Taranaki Region,Christmas New Year,Fine,Open,Hill Road,Nil,1.677466e+06,5.653355e+06,725105,NaN,...,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,Otago Region,Easter,Fine,Urban,Flat,Nil,1.404458e+06,4.914406e+06,869799,NaN,...,71.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN
990,Manawatū-Whanganui Region,Easter,Fine,Open,Flat,Nil,1.805917e+06,5.560702e+06,869805,NaN,...,38.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN
991,Auckland Region,Christmas New Year,Fine,Urban,Hill Road,Nil,1.744506e+06,5.922538e+06,869821,NaN,...,76.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN
992,Otago Region,Easter,Fine,Urban,Flat,Nil,1.406704e+06,4.917074e+06,869865,NaN,...,71.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
993,Auckland Region,Christmas New Year,Fine,Urban,Flat,Nil,1.770315e+06,5.917994e+06,869881,NaN,...,76.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [240]:
summ_aggregations = {}
cols_summ = []
for num_col in num_cols:
    summ_aggregations[num_col] = [ "min" , "max" , "mean" , "std" ]
    cols_summ.append( f"{num_col}_min" )
    cols_summ.append( f"{num_col}_max" )
    cols_summ.append( f"{num_col}_mean" )
    cols_summ.append( f"{num_col}_std" )

In [248]:
df_summ = df_clean.groupby(
    cat_cols_analisis
    , as_index=False
).agg(summ_aggregations)
df_summ.columns = cat_cols_analisis +  cols_summ

In [250]:
cantidad = 100000

In [252]:
def trunc_vector(min_val, max_val, media, desv_std,size):
    a, b = (min_val - media) / desv_std, (max_val - media) / desv_std
    
    muestras = truncnorm.rvs(a, b, loc=media, scale=desv_std, size=size)
    return muestras

In [ ]:
dfextended = pd.DataFrame()
for i in frequencia.index:
    setting = {
        "id": ids[ ids == i ]
    }
    for c in num_cols:
        setting[c] = trunc_vector( 
            df_summ.iloc[i][f"{c}_min"]
            , df_summ.iloc[i][f"{c}_max"]
            , df_summ.iloc[i][f"{c}_mean"]
            , df_summ.iloc[i][f"{c}_std"]
            , len( ids[ ids == i ] )
        )
    tmp = pd.DataFrame(setting)
    dfextended = pd.concat( [ dfextended , tmp ] )